spring:
  ldap:
    # Embedded Spring LDAP
    embedded:
      base-dn: dc=packtpub,dc=com
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:ldap/ldapschema.ldif
      port: 8389
      validation:
        enabled: false

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
